name: Deploy 233park-web to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - '233park-web/**'  # 只有当233park-web目录有变化时才触发
  
  workflow_dispatch:  # 允许手动触发

# 设置权限
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/Vue.js-Study/233park-web/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './233park-web/package-lock.json'
      
      - name: Install dependencies 
        working-directory: ./233park-web
        run: npm install
        
      - name: Build
        working-directory: ./233park-web
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # 确保dist目录有.nojekyll文件和404.html用于SPA
      - name: Setup SPA routing
        working-directory: ./233park-web/dist
        run: |
          touch .nojekyll
          cp index.html 404.html
          # 添加SPA路由重定向脚本到404.html
          sed -i 's/<\/head>/<script>\
          (function(){\
            var l = window.location;\
            l.replace(\
              l.protocol + "\/\/" + l.hostname + (l.port ? ":" + l.port : "") +\
              "\/Vue.js-Study\/233park-web\/" +\
              l.pathname.split("/").slice(3).join("/")\
            );\
          })();\
          <\/script><\/head>/g' 404.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./233park-web/dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 