name: 部署到GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3.5.3

      - name: 设置Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '233park-web/package-lock.json'
      
      - name: 安装依赖和构建
        working-directory: 233park-web
        run: |
          npm ci
          npm run build
      
      - name: 设置部署环境
        run: |
          # 创建部署目录
          mkdir -p deploy_temp/233park-web
          # 复制构建后的文件
          cp -r 233park-web/dist/* deploy_temp/233park-web/
          # 如果有vite.svg就复制，没有就创建空文件
          if [ -f "233park-web/vite.svg" ]; then
            cp 233park-web/vite.svg deploy_temp/233park-web/
          elif [ -f "233park-web/dist/vite.svg" ]; then
            cp 233park-web/dist/vite.svg deploy_temp/233park-web/
          else
            touch deploy_temp/233park-web/favicon.ico
          fi
          # 添加.nojekyll文件
          touch deploy_temp/233park-web/.nojekyll
          # 复制根目录文件
          cp index.html deploy_temp/
          if [ -f "404.html" ]; then
            cp 404.html deploy_temp/
          fi
          touch deploy_temp/.nojekyll

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_temp
          force_orphan: true 