name: 部署到GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3.5.3

      - name: 设置Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '233park-web/package-lock.json'
      
      - name: 安装依赖
        working-directory: 233park-web
        run: npm ci

      - name: 构建项目
        working-directory: 233park-web
        run: npm run build

      - name: 准备部署文件
        run: |
          cp -r 233park-web/dist/* .
          touch .nojekyll
      
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: . 